version: 0.9.2-beta-{build}
os: Visual Studio 2015
shallow_clone: true
install:
- ps: $Env:DNX_BUILD_VERSION = $Env:APPVEYOR_REPO_COMMIT.Substring(0,7)
- cmd: echo %DNX_BUILD_VERSION%
- cmd: echo %WEBPROJ_ENABLEBETA8RENAMES%
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cmd: dnvm update-self
- cmd: dnvm install 1.0.0-rc1-update1
- cmd: dnu restore --quiet --parallel
build_script:
- cmd: cd %APPVEYOR_BUILD_FOLDER%\src\LunoClient
- cmd: dnu build
- cmd: dnu pack --configuration RELEASE
artifacts:
  - path: '**\*.nupkg'
cache:
  - C:\Users\appveyor\.dnx
test_script:
- cmd: cd %APPVEYOR_BUILD_FOLDER%\test\LunoClient.Test
- cmd: dnx test
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: AbZSxh49fLFQDHwp+LlQjT2KPtMFJlcDKWq3KKHrsgNDxdRtOkJdU0ASJFTS/Vsk
  on:
    branch: master
environment:
  LUNO_API_KEY:
    secure: w3hm0PKirD7EPUyrmmOV+H4JLZ2c/pZ5CfiJO5ZlTbvlMdXrx+GmwPDO8nrciHRv
  LUNO_SECRET_KEY:
    secure: ps+ErvU3vlPKhEEeYCOJIyD2bQtGAgqkx6XB6gC4+LVLm78cpdjumm+0WwISTE9S7UCGttIqSnGQjgWXnIfX2L/73JPWGOQ0r7DevE7mK0E=
