version: 0.9.3-beta-{build}
os: Visual Studio 2015
shallow_clone: true
install:
- ps: $Env:DNX_BUILD_VERSION = $Env:APPVEYOR_REPO_COMMIT.Substring(0,7)
- cmd: echo %DNX_BUILD_VERSION%
- cmd: echo %WEBPROJ_ENABLEBETA8RENAMES%
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cmd: dnvm update-self
- cmd: dnvm install 1.0.0-rc1-update1
- cmd: dnu restore --quiet --parallel
build_script:
- cmd: cd %APPVEYOR_BUILD_FOLDER%\src\LunoClient
- cmd: dnu build
- cmd: dnu pack --configuration RELEASE
artifacts:
  - path: '**\*.nupkg'
cache:
  - C:\Users\appveyor\.dnx
test_script:
- cmd: cd %APPVEYOR_BUILD_FOLDER%\test\LunoClient.Test
- cmd: dnx test
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: AbZSxh49fLFQDHwp+LlQjT2KPtMFJlcDKWq3KKHrsgNDxdRtOkJdU0ASJFTS/Vsk
  on:
    branch: master
environment:
  LUNO_API_KEY:
    secure: /zPbDE5qu5KBezIQ6hTEuhfatddQH5GsxMpZ+5TYOObTm836MSst94ybssW9JNGI
  LUNO_SECRET_KEY:
    secure: To49hBqeh4x9Vtyhze2AtG5a90PkQOOhQ/WZ6ORMVhG0aNk9Yx1OOpwA6E41Xim8K9seaJzJK16j0Zr29ElVUBlKnOjit4vLUsnZvAtPDyE=
